CREATE TABLE user_account (
  id BIGSERIAL PRIMARY KEY,
  user_name VARCHAR(300) NOT NULL UNIQUE,
  password TEXT NOT NULL UNIQUE,
  authority VARCHAR(10) NOT NULL,
  create_at TIMESTAMP WITH TIME ZONE NOT NULL,
  update_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version INTEGER NOT NULL
);
